[project]
name = "pw-manager"
version = "0.1.0"
description = "Simple CLI Tool to manage and view passwords"
requires-python = ">=3.12"
dependencies = ["python-dotenv>=1.1.1"]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
